name: Main

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    permissions:
      security-events: write

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Get Token
        id: get_workflow_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.ADVANCED_SECURITY_APP_ID }}
          application_private_key: ${{ secrets.ADVANCED_SECURITY_APP_KEY }}

      - name: Install Deps
        run: python3 -m pip install pipenv && python3 -m pipenv install

      # Run Validation
      - name: Run Validation
        env:
          GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
        run: |
          pipenv run python ./.github/scripts/validate.py \
            --validate
